CREATE DATABASE SAN_PABLO

USE DATABASE SAN_PABLO;

CREATE TABLE category(
  id INT(10)  NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  PRIMARY KEY(id)
);


CREATE TABLE teams(
  id INT(10)  NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  date_f DATE NOT NULL,
  category VARCHAR(64) NOT NULL,
  president VARCHAR(64) NOT NULL,
  mail VARCHAR(64) NOT NULL,
  phone INT(10) NOT NULL,
  PRIMARY KEY(id)
);
