CREATE DATABASE SAN_PABLO

USE DATABASE SAN_PABLO;

CREATE TABLE category(
  id INT(10)  NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  PRIMARY KEY(id)
);


CREATE TABLE teams(
  id INT(10)  NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  date_f DATE NOT NULL,
  category VARCHAR(64) NOT NULL,
  president VARCHAR(64) NOT NULL,
  mail VARCHAR(64) NOT NULL,
  phone INT(10) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE players(
  id INT(10)  NOT NULL,
  name VARCHAR(64) NOT NULL,
  last_name VARCHAR(64) NOT NULL,
  cellphone INT(10) NOT NULL,
  address VARCHAR(64) NOT NULL,
  date_n DATE NOT NULL,
  team VARCHAR(64) NOT NULL,
  number_player VARCHAR(2) NOT NULL,
  mail VARCHAR(64) NOT NULL,
  PRIMARY KEY(id)
);
